# -*- coding: utf-8 -*-
"""IOII_dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h571g4xNXIHCtwxmQQXALd8dPUwScjvt
"""

import streamlit as st
import pandas as pd
import gurobipy as gp
from gurobipy import GRB
import matplotlib.pyplot as plt
import math

# --- 1. CONFIGURAÇÃO DA PÁGINA ---
st.set_page_config(page_title="Dashboard IOII - Burrito Game", layout="wide")
st.title("🌮 Burrito Game - Otimização de Frota (IOII)")
st.markdown("Faça o upload do seu ficheiro Excel com os dados do problema para começar.")

# --- 2. UPLOAD DO FICHEIRO EXCEL ---
uploaded_file = st.file_uploader("Arraste e solte o ficheiro Excel (.xlsx) aqui", type=["xlsx"])

if uploaded_file is not None:
    try:
        # Lê os dados diretamente da memória do browser (aceita qualquer nome de ficheiro)
        df_demand = pd.read_excel(uploaded_file, sheet_name='demand_node_data')
        df_truck = pd.read_excel(uploaded_file, sheet_name='truck_node_data')
        df_prob = pd.read_excel(uploaded_file, sheet_name='problem_data')
        df_dt = pd.read_excel(uploaded_file, sheet_name='demand_truck_data')
        df_dt = df_dt[['demand_node_index', 'truck_node_index', 'scaled_demand']].dropna()
    except Exception as e:
        st.error(f"⚠️ Erro ao ler o Excel! Certifique-se de que o ficheiro tem as abas corretas ('demand_node_data', etc.). Detalhe: {e}")
        st.stop()

    # Extrair parâmetros base do ficheiro carregado
    default_r = float(df_prob['burrito_price'].iloc[0])
    default_k = float(df_prob['ingredient_cost'].iloc[0])

    # --- 3. BARRA LATERAL (PARÂMETROS E RESTRIÇÕES) ---
    st.sidebar.header("⚙️ Parâmetros Financeiros")
    r = st.sidebar.number_input("Preço de Venda do Burrito (€)", min_value=1.0, value=default_r, step=0.5)
    k_ing = st.sidebar.number_input("Custo dos Ingredientes (€)", min_value=0.5, value=default_k, step=0.5)

    st.sidebar.markdown("---")
    st.sidebar.header("🚚 Frota (Tamanhos e Custos)")
    col_cap, col_cost = st.sidebar.columns(2)

    with col_cap:
        cap_P = st.number_input("Cap. Pequeno", min_value=10, value=25, step=5)
        cap_M = st.number_input("Cap. Médio", min_value=10, value=50, step=5)
        cap_G = st.number_input("Cap. Grande", min_value=10, value=100, step=10)

    with col_cost:
        cost_P = st.number_input("Custo Peq (€)", min_value=0, value=150, step=10)
        cost_M = st.number_input("Custo Méd (€)", min_value=0, value=250, step=10)
        cost_G = st.number_input("Custo Grd (€)", min_value=0, value=400, step=10)

    st.sidebar.markdown("---")
    st.sidebar.header("🛡️ Outras Restrições")
    use_min_trucks = st.sidebar.checkbox("Impor nº mínimo total de camiões?")
    min_trucks = st.sidebar.number_input("Nº Mínimo de Camiões", min_value=1, value=2, step=1) if use_min_trucks else 0

    use_min_dist = st.sidebar.checkbox("Impor distância mínima entre camiões?")
    min_dist = st.sidebar.number_input("Distância Mínima", min_value=10.0, value=100.0, step=10.0) if use_min_dist else 0.0

    # Tipos de Camiões (Dicionários para o Modelo)
    TIPOS = ['Pequeno', 'Médio', 'Grande']
    CAPACIDADE = {'Pequeno': cap_P, 'Médio': cap_M, 'Grande': cap_G}
    CUSTO_FIXO = {'Pequeno': cost_P, 'Médio': cost_M, 'Grande': cost_G}

    CORES_TAMANHO = {'Pequeno': 'lightblue', 'Médio': 'dodgerblue', 'Grande': 'darkblue'}
    SIZES_GRAFICO = {'Pequeno': 150, 'Médio': 300, 'Grande': 500}

    # --- 4. OTIMIZAÇÃO E DASHBOARD (Só corre ao clicar no botão) ---
    if st.button("🚀 Otimizar Frota (Correr Gurobi)", type="primary"):
        with st.spinner("A calcular a rede ótima com camiões de vários tamanhos..."):
            I = df_demand['index'].tolist()
            J = df_truck['index'].tolist()
            a = {(row['demand_node_index'], row['truck_node_index']): row['scaled_demand'] for _, row in df_dt.iterrows()}

            env = gp.Env(empty=True)
            env.setParam("OutputFlag", 0)
            env.start()
            model = gp.Model("Burrito_Game_MultiCapacity", env=env)

            # Variáveis de Decisão
            Y = model.addVars(J, TIPOS, vtype=GRB.BINARY, name="Y")
            X = model.addVars(I, J, vtype=GRB.BINARY, name="X")

            # Função Objetivo
            lucro_var = gp.quicksum((r - k_ing) * a.get((i, j), 0) * X[i, j] for i in I for j in J if (i, j) in a)
            custo_fixo_total = gp.quicksum(CUSTO_FIXO[t] * Y[j, t] for j in J for t in TIPOS)
            model.setObjective(lucro_var - custo_fixo_total, GRB.MAXIMIZE)

            # Restrições Base
            for i in I:
                model.addConstr(gp.quicksum(X[i, j] for j in J if (i, j) in a) <= 1)

            for j in J:
                model.addConstr(gp.quicksum(Y[j, t] for t in TIPOS) <= 1)

            for j in J:
                model.addConstr(
                    gp.quicksum(a.get((i, j), 0) * X[i, j] for i in I if (i, j) in a) <= gp.quicksum(CAPACIDADE[t] * Y[j, t] for t in TIPOS)
                )

            # Restrições Opcionais
            if use_min_trucks:
                model.addConstr(gp.quicksum(Y[j, t] for j in J for t in TIPOS) >= min_trucks)

            if use_min_dist:
                for j1 in J:
                    for j2 in J:
                        if j1 < j2:
                            row1 = df_truck[df_truck['index'] == j1].iloc[0]
                            row2 = df_truck[df_truck['index'] == j2].iloc[0]
                            dist = math.sqrt((row1['x'] - row2['x'])**2 + (row1['y'] - row2['y'])**2)
                            if dist < min_dist:
                                model.addConstr(gp.quicksum(Y[j1, t] for t in TIPOS) + gp.quicksum(Y[j2, t] for t in TIPOS) <= 1)

            # Resolver
            model.optimize()

            if model.Status == GRB.OPTIMAL:
                st.success("✅ Solução Ótima Encontrada!")

                opened_trucks = [(j, t) for j in J for t in TIPOS if Y[j, t].X > 0.5]

                # --- CÁLCULOS FINANCEIROS ---
                total_burritos = sum(a[(i,j)] for i in I for j in J if (i, j) in a and X[i, j].X > 0.5)
                faturacao = total_burritos * r
                custo_ingredientes = total_burritos * k_ing
                custo_frota = sum(CUSTO_FIXO[t] for j, t in opened_trucks)
                lucro_liquido = faturacao - custo_ingredientes - custo_frota

                # --- DASHBOARD FINANCEIRO ---
                st.subheader("📊 Resumo Financeiro da Operação")
                col1, col2, col3, col4 = st.columns(4)
                col1.metric("Faturação Total (Receitas)", f"{faturacao:.2f} €")
                col2.metric("Custo de Ingredientes", f"- {custo_ingredientes:.2f} €")
                col3.metric("Custo da Frota", f"- {custo_frota:.2f} €")
                col4.metric("Lucro Líquido", f"{lucro_liquido:.2f} €", delta="Máximo atingido")

                st.markdown("---")

                # --- GRÁFICO DO MAPA ---
                st.subheader("🗺️ Mapa Logístico da Operação")
                fig, ax = plt.subplots(figsize=(10, 6))

                ax.scatter(df_demand['x'], df_demand['y'], c='gray', s=30, label='Edifícios', alpha=0.5, zorder=2)

                for j, tipo in opened_trucks:
                    t_row = df_truck[df_truck['index'] == j].iloc[0]
                    ax.scatter(t_row['x'], t_row['y'], c=CORES_TAMANHO[tipo], marker='s', s=SIZES_GRAFICO[tipo], edgecolor='black', zorder=3, label=f'Camião {tipo}' if f'Camião {tipo}' not in ax.get_legend_handles_labels()[1] else "")
                    ax.text(t_row['x'], t_row['y'] + 10, f"{j}\n({tipo})", color='black', fontweight='bold', ha='center', fontsize=8)

                for i in I:
                    for j in J:
                        if (i, j) in a and X[i, j].X > 0.5:
                            d_row = df_demand[df_demand['index'] == i].iloc[0]
                            t_row = df_truck[df_truck['index'] == j].iloc[0]
                            ax.plot([d_row['x'], t_row['x']], [d_row['y'], t_row['y']], 'k-', alpha=0.2, zorder=1)

                handles, labels = plt.gca().get_legend_handles_labels()
                by_label = dict(zip(labels, handles))
                ax.legend(by_label.values(), by_label.keys(), loc='upper right')

                ax.set_title("Camiões por Capacidade (Azul Claro=Peq | Azul Médio=Méd | Azul Escuro=Grd)")
                ax.grid(True, linestyle=':', alpha=0.4)
                st.pyplot(fig)

                st.markdown("---")

                col_tab1, col_tab2 = st.columns(2)

                # --- TABELA 1: FROTA ---
                with col_tab1:
                    st.subheader("🚚 Camiões Instalados (Frota)")
                    frota_data = []
                    for j, tipo in opened_trucks:
                        vendas = sum(a.get((i, j), 0) * X[i, j].X for i in I if (i, j) in a)
                        frota_data.append({
                            "Camião": j,
                            "Tipo": tipo,
                            "Cap. Máx": CAPACIDADE[tipo],
                            "Vendas": int(vendas),
                            "Custo (€)": CUSTO_FIXO[tipo]
                        })
                    st.dataframe(pd.DataFrame(frota_data), use_container_width=True, hide_index=True)

                # --- TABELA 2: ALOCAÇÃO DOS EDIFÍCIOS ---
                with col_tab2:
                    st.subheader("🏢 Alocação de Edifícios (Clientes)")
                    alloc_data = []
                    for i in I:
                        for j in J:
                            if (i, j) in a and X[i, j].X > 0.5:
                                tipo_camiao = next(t for t in TIPOS if Y[j, t].X > 0.5)
                                alloc_data.append({
                                    "Edifício (Origem)": i,
                                    "Vai ao Camião...": j,
                                    "Tipo de Camião": tipo_camiao,
                                    "Burritos": int(a[(i,j)])
                                })
                    st.dataframe(pd.DataFrame(alloc_data), use_container_width=True, hide_index=True)

            elif model.Status == GRB.INFEASIBLE:
                st.error("❌ O Modelo é Inviável! Verifique as restrições introduzidas.")
            else:
                st.warning("⚠️ Não foi encontrada solução rentável.")

else:
    st.info("👆 Por favor, carregue o ficheiro Excel com os dados do 'Burrito Game' para desbloquear o simulador.")
