# -*- coding: utf-8 -*-
"""MQAD_dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KC-qmK3VbgCZl4DnuWzBedgOIxCLC8q6
"""

import pandas as pd
import streamlit as st
import plotly.express as px
import pydeck as pdk

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, roc_curve, confusion_matrix

st.set_page_config(page_title="Smart Logistics Dashboard", layout="wide")

@st.cache_data
def load_data(uploaded_file) -> pd.DataFrame:
    # Ler o Excel diretamente da memória (uploaded_file)
    df = pd.read_excel(uploaded_file, engine="openpyxl")
    df.columns = [c.strip() for c in df.columns]

    if "Timestamp" in df.columns:
        df["Timestamp"] = pd.to_datetime(df["Timestamp"], errors="coerce")

    if "Logistics_Delay" in df.columns:
        if df["Logistics_Delay"].dtype == bool:
            df["Logistics_Delay"] = df["Logistics_Delay"].astype(int)
        elif df["Logistics_Delay"].dtype == object:
            m = {"yes": 1, "no": 0, "sim": 1, "não": 0, "nao": 0, "true": 1, "false": 0}
            df["Logistics_Delay"] = (
                df["Logistics_Delay"]
                .astype(str).str.strip().str.lower()
                .map(m)
                .fillna(df["Logistics_Delay"])
            )
            df["Logistics_Delay"] = pd.to_numeric(df["Logistics_Delay"], errors="coerce")

    if "Traffic_Status" in df.columns and "tipo_trafico" not in df.columns:
        map_trafico = {"Clear": 1, "Heavy": 2, "Detour": 3}
        df["tipo_trafico"] = df["Traffic_Status"].map(map_trafico)

    return df


st.title("📦 Smart Logistics — Dashboard Interativo (MQAD)")
st.markdown("Faça o upload do dataset logístico em formato Excel para gerar as análises e o modelo preditivo.")

# -----------------------------
# Upload do Excel (Substitui o caminho estático)
# -----------------------------
uploaded_file = st.file_uploader("Arraste e solte o ficheiro Excel (.xlsx) aqui", type=["xlsx"])

if uploaded_file is not None:
    try:
        df = load_data(uploaded_file)
        st.success(f"Ficheiro `{uploaded_file.name}` carregado com sucesso!")
    except Exception as e:
        st.error(f"Não consegui ler o Excel. Erro: {e}")
        st.stop()

    # -----------------------------
    # Sidebar: Filters
    # -----------------------------
    st.sidebar.header("🔎 Filtros")

    # Date range
    if "Timestamp" in df.columns and df["Timestamp"].notna().any():
        min_dt = df["Timestamp"].min()
        max_dt = df["Timestamp"].max()
        dt_range = st.sidebar.date_input(
            "Intervalo de datas",
            value=(min_dt.date(), max_dt.date()),
            min_value=min_dt.date(),
            max_value=max_dt.date(),
        )
    else:
        dt_range = None

    # Categorical filters
    cat_cols = [c for c in ["Asset_ID", "Shipment_Status", "Traffic_Status", "Logistics_Delay_Reason"] if c in df.columns]
    selected = {}
    for c in cat_cols:
        opts = sorted([x for x in df[c].dropna().unique()])
        selected[c] = st.sidebar.multiselect(f"{c}", options=opts, default=opts)

    # Numeric filters
    num_cols = [c for c in [
        "Inventory_Level", "Temperature", "Humidity", "Waiting_Time",
        "User_Transaction_Amount", "User_Purchase_Frequency",
        "Asset_Utilization", "Demand_Forecast"
    ] if c in df.columns]

    num_ranges = {}
    for c in num_cols:
        s = pd.to_numeric(df[c], errors="coerce")
        if s.notna().any():
            lo = float(s.min())
            hi = float(s.max())
            num_ranges[c] = st.sidebar.slider(f"{c}", min_value=lo, max_value=hi, value=(lo, hi))

    # Target filter
    if "Logistics_Delay" in df.columns:
        delay_mode = st.sidebar.selectbox("Logistics_Delay", ["Todos", "Só atraso (1)", "Só não atraso (0)"])
    else:
        delay_mode = "Todos"

    # -----------------------------
    # Apply filters
    # -----------------------------
    f = df.copy()

    if dt_range and "Timestamp" in f.columns:
        start, end = dt_range
        start = pd.to_datetime(start)
        end = pd.to_datetime(end) + pd.Timedelta(days=1) - pd.Timedelta(seconds=1)
        f = f[(f["Timestamp"] >= start) & (f["Timestamp"] <= end)]

    for c in cat_cols:
        f = f[f[c].isin(selected[c])]

    for c, (lo, hi) in num_ranges.items():
        f[c] = pd.to_numeric(f[c], errors="coerce")
        f = f[(f[c] >= lo) & (f[c] <= hi)]

    if "Logistics_Delay" in f.columns:
        if delay_mode == "Só atraso (1)":
            f = f[f["Logistics_Delay"] == 1]
        elif delay_mode == "Só não atraso (0)":
            f = f[f["Logistics_Delay"] == 0]

    # -----------------------------
    # KPIs
    # -----------------------------
    c1, c2, c3, c4 = st.columns(4)
    total = len(f)
    c1.metric("Registos (após filtros)", f"{total:,}".replace(",", "."))

    if "Logistics_Delay" in f.columns and total > 0:
        c2.metric("Taxa de atraso", f"{pd.to_numeric(f['Logistics_Delay'], errors='coerce').mean()*100:.2f}%")
    else:
        c2.metric("Taxa de atraso", "—")

    if "Waiting_Time" in f.columns and total > 0:
        c3.metric("Waiting_Time (média)", f"{pd.to_numeric(f['Waiting_Time'], errors='coerce').mean():.2f}")
    else:
        c3.metric("Waiting_Time (média)", "—")

    if "Inventory_Level" in f.columns and total > 0:
        c4.metric("Inventory_Level (média)", f"{pd.to_numeric(f['Inventory_Level'], errors='coerce').mean():.2f}")
    else:
        c4.metric("Inventory_Level (média)", "—")

    st.divider()

    # -----------------------------
    # Tabs
    # -----------------------------
    tab1, tab2, tab3, tab4 = st.tabs(["📈 Visão Geral", "🗺️ Mapa", "🔗 Correlações", "🤖 Modelo (Logística)"])

    with tab1:
        left, right = st.columns([1.2, 1])

        with left:
            st.subheader("Distribuição do atraso")

            if "Logistics_Delay" in f.columns and total > 0:
                fig = px.histogram(
                    f,
                    x="Logistics_Delay",
                    color="Logistics_Delay",
                    barmode="group",
                    color_discrete_map={
                        0: "#2ECC71",  # verde – sem atraso
                        1: "#E74C3C",  # vermelho – com atraso
                    },
                    labels={"Logistics_Delay": "Atraso Logístico"}
                )
                fig.update_layout(
                    xaxis=dict(
                        tickmode="array",
                        tickvals=[0, 1],
                        ticktext=["Sem atraso", "Com atraso"]
                    ),
                    legend_title_text="Estado"
                )
                st.plotly_chart(fig, use_container_width=True)
            else:
                st.info("Sem coluna Logistics_Delay ou sem dados após filtros.")

        with right:
            st.subheader("Boxplot por categoria")
            y_col = st.selectbox("Variável numérica", options=num_cols if num_cols else ["—"])
            x_col = st.selectbox("Categoria", options=cat_cols if cat_cols else ["—"])

            if y_col != "—" and x_col != "—" and total > 0:
                st.plotly_chart(px.box(f, x=x_col, y=y_col, points="outliers"), use_container_width=True)
            else:
                st.info("Escolhe uma variável numérica e uma categoria (e garante que há dados).")

            st.subheader("Tabela (amostra)")
            st.dataframe(f.head(50), use_container_width=True)

    with tab2:
        st.subheader("Mapa (Latitude/Longitude)")

        if {"Latitude", "Longitude"}.issubset(f.columns) and total > 0:
            geo = f.dropna(subset=["Latitude", "Longitude"]).copy()
            geo["Latitude"] = pd.to_numeric(geo["Latitude"], errors="coerce")
            geo["Longitude"] = pd.to_numeric(geo["Longitude"], errors="coerce")
            geo = geo.dropna(subset=["Latitude", "Longitude"])

            if len(geo) == 0:
                st.info("Não há pontos válidos (lat/long) após filtros.")
            else:
                view = pdk.ViewState(
                    latitude=float(geo["Latitude"].mean()),
                    longitude=float(geo["Longitude"].mean()),
                    zoom=9,
                    pitch=0,
                )

                st.pydeck_chart(pdk.Deck(
                    initial_view_state=view,
                    layers=[
                        pdk.Layer(
                            "ScatterplotLayer",
                            data=geo,
                            get_position="[Longitude, Latitude]",
                            get_radius=150,
                            pickable=True,
                            auto_highlight=True,
                        )
                    ],
                ))
        else:
            st.info("Precisas de colunas Latitude e Longitude (e dados após filtros).")

    with tab3:
        st.subheader("Matriz de correlação (numéricas)")

        if len(num_cols) >= 2 and total > 5:
            corr_df = f[num_cols].apply(pd.to_numeric, errors="coerce")
            corr = corr_df.corr(numeric_only=True)
            st.plotly_chart(px.imshow(corr, text_auto=True, aspect="auto"), use_container_width=True)
        else:
            st.info("Poucas variáveis numéricas ou poucos dados após filtros.")

    with tab4:
        st.subheader("Modelo de Regressão Logística")
        st.caption("Previsões de atraso (0/1) baseadas nas variáveis selecionadas.")

        if "Logistics_Delay" not in f.columns:
            st.info("Não existe a coluna Logistics_Delay.")
        elif total < 50:
            st.info("Poucos dados após filtros para treinar um modelo de forma fiável.")
        else:
            default_features = [c for c in [
                "Waiting_Time", "Temperature", "Inventory_Level", "Humidity",
                "Traffic_Status", "Shipment_Status", "Asset_ID", "Asset_Utilization",
                "User_Transaction_Amount", "User_Purchase_Frequency", "Demand_Forecast"
            ] if c in f.columns]

            features = st.multiselect("Features do modelo", options=list(f.columns), default=default_features)

            if len(features) == 0:
                st.warning("Escolhe pelo menos 1 feature para treinar o modelo.")
            else:
                X = f[features].copy()
                y = pd.to_numeric(f["Logistics_Delay"], errors="coerce")

                mask = y.notna()
                X = X.loc[mask]
                y = y.loc[mask].astype(int)

                cat = [c for c in X.columns if X[c].dtype == "object"]
                num = [c for c in X.columns if c not in cat]

                pre = ColumnTransformer(
                    transformers=[
                        ("num", Pipeline([("imp", SimpleImputer(strategy="median"))]), num),
                        ("cat", Pipeline([
                            ("imp", SimpleImputer(strategy="most_frequent")),
                            ("oh", OneHotEncoder(handle_unknown="ignore"))
                        ]), cat),
                    ],
                    remainder="drop"
                )

                clf = Pipeline(steps=[
                    ("pre", pre),
                    ("lr", LogisticRegression(max_iter=2000))
                ])

                X_train, X_test, y_train, y_test = train_test_split(
                    X, y, test_size=0.25, random_state=42, stratify=y if y.nunique() == 2 else None
                )

                clf.fit(X_train, y_train)
                proba = clf.predict_proba(X_test)[:, 1]
                auc = roc_auc_score(y_test, proba) if y_test.nunique() == 2 else None

                colA, colB = st.columns(2)
                with colA:
                    st.write("**Desempenho: Área sob a Curva (AUC)**")
                    st.write("—" if auc is None else round(float(auc), 4))

                with colB:
                    if auc is not None:
                        fpr, tpr, _ = roc_curve(y_test, proba)
                        roc_df = pd.DataFrame({"FPR": fpr, "TPR": tpr})
                        st.plotly_chart(px.line(roc_df, x="FPR", y="TPR", title="Curva ROC"), use_container_width=True)
                    else:
                        st.info("Não foi possível calcular a curva ROC (precisa de exemplos com e sem atraso no teste).")

else:
    st.info("👆 Por favor, carregue o ficheiro Excel com o dataset logístico para iniciar as análises.")